### ISSUE TITLE
Installed from Webstore, extension is not working 

### ISSUE THREAD

**Issue by millermk1717** [evandor/tabsets#25]
Hi there, I was really excited with the direction of your extension as I am constantly looking for a better way to manage tabs, sessions, and bookmarks. I installed via the webstore but the extension did not work. I reloaded it and also went to the chrome-extension://afkknkdbgondbbfjehipnjmojndnjhjg/ page where it said:

Your file couldn’t be accessed
It may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND

I am on Mac if it matters. I hope its ok to post here and I hope to hear from you, as I said, I love the direction you've been taking it. I might try to download the crx and load as a developer.

**Comment by evandor** [comment]
Hi there, and thanks a lot for reaching out! 

I assume you were using a recent version of chrome? When you say "did not work", so you mean that nothing happened, i.e. no new tab with the extension opened? But the extension was listed in the "manage extension" page (as you were able to reload it), right? 

Did you start with a blank new window (no other tabs than the 'new tab' one)? It seems like I can reproduce this behaviour in that case...

As a workaround for now, could you try this link instead (with the extension being already installed):

chrome-extension://afkknkdbgondbbfjehipnjmojndnjhjg/www/index.html

(that's your original link with "/www/index.html" added).

Please let me know about your findings and if the link above actually did work.

Cheers
Carsten

**Comment by evandor** [comment]
Expecting fix in next version (0.3.1). Tab for extension is now explicitly opened by the extension, not by browser default.

**Comment by evandor** [comment]
the new version (0.3.1) is released now and this bug should be fixed.
